In [1]:
  import torch

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[9.2755e-39, 1.0837e-38, 8.4490e-39],
        [1.1112e-38, 1.0194e-38, 9.0919e-39],
        [8.4490e-39, 9.6429e-39, 8.4490e-39],
        [9.6429e-39, 9.2755e-39, 1.0286e-38],
        [9.0919e-39, 8.9082e-39, 9.2755e-39]])


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.3201, 0.5905, 0.7827],
        [0.9547, 0.8112, 0.2659],
        [0.9351, 0.3322, 0.9539],
        [0.5872, 0.4249, 0.0867],
        [0.8249, 0.0900, 0.5031]])


In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.8604,  0.6796,  0.3208],
        [ 1.7679,  1.1537,  0.8378],
        [-1.1623,  0.4861,  2.2621],
        [-0.7962, -1.5976, -0.9594],
        [ 1.2736, -0.4528,  1.8274]])


In [7]:
print(x.size())

torch.Size([5, 3])


In [13]:
y = torch.rand(5, 3)
print(y)
print(x + y)

tensor([[0.6593, 0.0413, 0.2862],
        [0.0765, 0.7656, 0.0966],
        [0.7200, 0.3816, 0.3143],
        [0.6853, 0.9745, 0.6005],
        [0.6719, 0.8103, 0.3635]])
tensor([[ 1.5196,  0.7209,  0.6070],
        [ 1.8445,  1.9193,  0.9344],
        [-0.4423,  0.8677,  2.5764],
        [-0.1109, -0.6231, -0.3589],
        [ 1.9454,  0.3575,  2.1909]])


In [14]:
print(torch.add(x, y))

tensor([[ 1.5196,  0.7209,  0.6070],
        [ 1.8445,  1.9193,  0.9344],
        [-0.4423,  0.8677,  2.5764],
        [-0.1109, -0.6231, -0.3589],
        [ 1.9454,  0.3575,  2.1909]])


In [15]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.5196,  0.7209,  0.6070],
        [ 1.8445,  1.9193,  0.9344],
        [-0.4423,  0.8677,  2.5764],
        [-0.1109, -0.6231, -0.3589],
        [ 1.9454,  0.3575,  2.1909]])


In [16]:
y.add_(x)
print(y)

tensor([[ 1.5196,  0.7209,  0.6070],
        [ 1.8445,  1.9193,  0.9344],
        [-0.4423,  0.8677,  2.5764],
        [-0.1109, -0.6231, -0.3589],
        [ 1.9454,  0.3575,  2.1909]])


In [17]:
print(x[:, 1])

tensor([ 0.6796,  1.1537,  0.4861, -1.5976, -0.4528])


In [18]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [19]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.9445])
-1.9444690942764282


Converting a Torch Tensor to a NumPy Array

In [20]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [21]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


The Torch Tensor and NumPy array will share their underlying memory locations (if the Torch Tensor is on CPU), and changing one will change the other.

In [22]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [23]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


### CUDA Tensors
Tensors can be moved onto any device using the `.to` method.

In [24]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))

tensor([-0.9445], device='cuda:0')
tensor([-0.9445], dtype=torch.float64)


In [1]:
import os
os.getcwd()

'F:\\python_work\\pytorch_tutorials'